version: '3.8'

services:
  web:
    image: artpv/myfirstrepo:web
    # build: ./app
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    # command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    volumes:
      - ./app/:/usr/src/app/
      - ./app/staticfiles:/home/app/web/staticfiles
    
    # ports:
    #   - 8000:8000
    expose:
    - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  nginx:
    image: artpv/myfirstrepo:nginx
    # build: ./nginx
    volumes:
      - ./app/staticfiles:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
